#!/usr/bin/bash

## This is incorrect script line - There is duplicate flags:
python3 regex_finder.py -r [a-z][o][a-z] -f files/song1.txt -m -c 
python3 regex_finder.py -r [a-z][o][a-z] -f files/song1.txt -u -c


 ## Lets try so search in files song1.txt and song2.txt all The [a-z][o][a-z] regex 
python3 regex_finder.py -r [a-z][o][a-z] -f files/song1.txt -m  ## you can change it to -u or -c
python3 regex_finder.py -r [a-z][o][a-z] -f files/song1.txt -c  ## you can change it to -m or -u
python3 regex_finder.py -r [a-z][o][a-z] -f files/song2.txt -u  ## you can change it to -m or -c

## There is more files you can try on the 'files' folder.